name: API Proxy
on:
  workflow_dispatch:
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Hugging Face API
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $HF_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"inputs":"${{ github.event.inputs.prompt }}"}' \
            https://api-inference.huggingface.co/models/deepseek-ai/DeepSeek-R1-0528
